language: generic

os: osx
osx_image: xcode9.4

before_install:
  - brew update
  - bash ./build-openexr.sh
  - ls
  - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
  - bash  ./upload_rotate.sh "continuous" *bottle*.tgz >& /dev/null

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
